# 'A', 'C', 'G', 'T'

base_idx = {'A': 0,
            'C': 1,
            'G': 2,
            'T': 3}

gt_decoded_labels = ['AA',
                     'AC',
                     'AG',
                     'AT',
                     'CC',
                     'CG',
                     'CT',
                     'GG',
                     'GT',
                     'TT',
                     'DD',
                     'AD',
                     'CD',
                     'GD',
                     'TD',
                     'II',
                     'AI',
                     'CI',
                     'GI',
                     'TI',
                     'ID']

zy_decoded_labels = ['0/0', '1/1', '0/1']

indel1_decoded_labels = ['<-15',
                         '-15',
                         '-14',
                         '-13',
                         '-12',
                         '-11',
                         '-10',
                         '-9',
                         '-8',
                         '-7',
                         '-6',
                         '-5',
                         '-4',
                         '-3',
                         '-2',
                         '-1',
                         '0',
                         '1',
                         '2',
                         '3',
                         '4',
                         '5',
                         '6',
                         '7',
                         '8',
                         '9',
                         '10',
                         '11',
                         '12',
                         '13',
                         '14',
                         '15',
                         '>15']

indel2_decoded_labels = indel1_decoded_labels
